spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.57.70.149:3306/taobao?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181